### ISSUE TITLE
Change the information in README to be more accurate

### ISSUE THREAD

**Issue by seanshin2647** [seanshin2647/BUBC-Universal-Bookmark-Converter#10]
The README's statements are factually incorrect.
Please delete 
"While desktop browsers generally have sufficient built-in tools for transferring bookmarks, especially with the popular browsers like Firefox, Microsoft Edge, Internet Explorer, or Opera, many mobile browsers, especially more niche or less known ones generally do not have tools to transfer bookmarks between browsers. Even popular mobile browsers like Firefox Mobile cannot import bookmarks unless done so in an indirect manner such as going through the desktop application and then enabling sync."

**Comment by JoshYoung2693** [comment]
I can do it

**Comment by seanshin2647** [comment]
Got it. Thank you.

**Comment by seanshin2647** [comment]
Closed with PR #11.
