### ISSUE TITLE
Main Java?

### ISSUE THREAD

**Issue by KingOfBlackKatz** [seanshin2647/BUBC-Universal-Bookmark-Converter#7]
I was looking through the files and ran across Main.java. From the title, is it safe to assume that this will be the main Java file? And, if so, shouldn't there be a main class in there instead of a class called Main?

**Comment by seanshin2647** [comment]
Yeah, you're right. I haven't actually done anything with it and just left it there for now.

**Comment by seanshin2647** [comment]
Wait, reading through it again, I don't exactly understand what you're asking. Do you mean that there should be a method in the Main class in Main.java titled "main"? If so, yes, you're right. I just haven't done anything with it and left the file there as a placeholder.

**Comment by KingOfBlackKatz** [comment]
Well, generally, concerning Java files, there should be a "main"... well, method... which is generally written along the lines of "public static void main()". That's all I'm saying. There is some significance to this "main method" but I can't remember what significance it had.

**Comment by KingOfBlackKatz** [comment]
Looking back at it, all that it needs is that new "method".
